GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "Javascript is awesome!",
    "author": "JJ",
    "url": "http://jj.com",
    "likes": 10
}

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "author": "JJ"
}

###

DELETE  http://localhost:3003/api/blogs/615ba8f368f5f375229e48b2

